site_name: webMethods Documentation
docs_dir: docs
theme:
  name: material
markdown_extensions:
- tables
- fenced_code
nav:
- Home: index.md
- Business Summary: business-summary.md
- Summary: reports/summary.md
- Services:
  - com.example.billing:createInvoice: services/com/example/billing/createInvoice.md
  - com.example.customer:validateCustomer: services/com/example/customer/validateCustomer.md
  - com.example.order:submitOrder: services/com/example/order/submitOrder.md
- Documents:
  - com.example.docs:Order: documents/com/example/docs/Order.md
- Processes:
  - Order Submission: processes/order-submission.md
